INSERT ALL
    INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_1', 'NO', '', '', 'No opinion', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_1', 'WE', '', '', 'Weak', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_1', 'BA', '', '', 'Below average', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_1', 'AV', '', '', 'Average', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_1', 'AA', '', '', 'Above average', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_1', 'ST', '', '', 'Strong', '01-Jan-00', '31-Dec-12')
SELECT 1 FROM DUAL;



INSERT ALL
    INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_2', 'NT', '', '', 'Negative Trend', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_2', 'SE', '', '', 'Securities Existing', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_2', 'SP', '', '', 'Special Commitment', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_2', 'WL', '', '', 'Watchlist', '01-Jan-00', '31-Dec-12')
SELECT 1 FROM DUAL;



INSERT ALL
    INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_3', '1', '', '', 'Public', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_3', '2', '', '', 'Confidential', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_3', '3', '', '', 'Strictly Confidential', '01-Jan-00', '31-Dec-12')
SELECT 1 FROM DUAL;



INSERT ALL
    INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_4', '1', '', '', 'Limit Appeal', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_4', '2', '', '', 'Limit Chaser', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_4', '3', '', '', 'Limit Complaint', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_4', '4', '', '', 'Buyer Financial Information', '01-Jan-00', '31-Dec-12')
SELECT 1 FROM DUAL;



INSERT ALL
    INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '1', '', '', 'Public', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '2', '', '', 'SRM', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '3', '', '', 'Watchlist', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '4', '', '', 'Observing', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '5', '', '', 'Warning', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '6', '', '', 'LCC', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '7', '', '', 'GCC', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '8', '', '', 'LBU', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_5', '9', '', '', 'Impersonation', '01-Jan-00', '31-Dec-12')
SELECT 1 FROM DUAL;



INSERT ALL
    INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_6', 'EU', '', '', 'Euro', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_6', 'DL', '', '', 'Dolar', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_6', 'LR', '', '', 'Lira', '01-Jan-00', '31-Dec-12')
	INTO TBBM_REF_DATA_BUYERS (DOMAIN_NAME, CODE_VAL1, CODE_VAL2, CODE_VAL3, CODE_DES, EFFECT_FROM_DAT, EFFECT_TO_DAT) VALUES ('DOMAIN_EXAMPLE_6', 'YE', '', '', 'Yen', '01-Jan-00', '31-Dec-12')
SELECT 1 FROM DUAL;



